# Generated by Django 4.2.2 on 2023-07-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningpoint',
            name='session_id',
        ),
    ]
