# Generated by Django 4.2.2 on 2023-07-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_earningpoint_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningpoint',
            name='streak',
        ),
    ]
