# Generated by Django 4.2.2 on 2023-07-07 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
