# Generated by Django 4.2.2 on 2023-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unipay_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='unipay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
