# Generated by Django 4.2.2 on 2023-07-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_banner_size_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='size',
        ),
    ]
