# Generated by Django 4.2.2 on 2023-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_remove_banner_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.CharField(choices=[('x1', 'Height 1'), ('x2', 'Height 2'), ('x3', 'Height 3')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
