# Generated by Django 4.2.2 on 2023-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_banner_image_height_banner_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.URLField(default=True),
        ),
    ]
