# Generated by Django 4.2.2 on 2023-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_alter_banner_button_link_alter_banner_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
