# Generated by Django 4.2.2 on 2023-07-11 17:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_alter_banner_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
