# Generated by Django 4.2.2 on 2023-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_banner_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_second',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner_second',
            name='image',
            field=models.ImageField(default=0, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
