# Generated by Django 4.2.2 on 2023-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_total_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_mode', models.BooleanField(default=False)),
                ('allowed_hosts', models.TextField(blank=True)),
            ],
        ),
    ]
